Improvements from old IMDG scripts + removed IMDG scripts

diff --git a/distribution/src/bin-filemode-755/hz-cluster-cp-admin b/distribution/src/bin-filemode-755/hz-cluster-cp-admin
--- a/distribution/src/bin-filemode-755/hz-cluster-cp-admin
+++ b/distribution/src/bin-filemode-755/hz-cluster-cp-admin
@@ -142,7 +142,7 @@ if [[ -z "$ADDRESS" ]]; then
     ADDRESS="127.0.0.1"
 fi
 
-command -v curl >/dev/null 2>&1 || { echo >&2 "Cluster state script requires curl but it's not installed. Aborting."; exit 255; }
+command -v curl >/dev/null 2>&1 || { echo >&2 "Cluster state script requires curl but it's not installed. Aborting."; exit 1; }
 
 URL_BASE="${URL_SCHEME}://${ADDRESS}:${PORT}/hazelcast/rest/cp-subsystem"
 CURL_CMD="curl $CURL_ARGS"
